const SUCCESS = 200;
const NOT_FOUND = 404;
const SERVER_ERROR = 500;
const DATABASE_ERROR = 200;
const UNAUTHORIZED = 401;
const BAD_REQUEST = 400;
const CREATED = 201;
const EXIST = 403;

module.exports = {
	SUCCESS,
	NOT_FOUND,
	SERVER_ERROR,
	DATABASE_ERROR,
	UNAUTHORIZED,
	BAD_REQUEST,
	CREATED,
	EXIST,
};
